[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["python"]

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py ensure_superuser && gunicorn config.wsgi --bind 0.0.0.0:$PORT --access-logfile - --error-logfile -"
