[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["python"]

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 30
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT --access-logfile - --error-logfile -"
